import React from 'react';
import PredictionBadge from './PredictionBadge';
import { AlertCircle, Gauge, Car, ShieldAlert, CheckCircle, Activity, Info } from 'lucide-react';

export default function HotspotDetail({ hotspot }) {
  if (!hotspot) {
    return (
      <div className="bg-surface/50 border border-surface-border rounded-xl p-8 text-center text-slate-400">
        <Info className="w-8 h-8 text-slate-400 mx-auto mb-3 opacity-60" />
        <p className="text-sm">Select a corridor from the hotspot list or map to view technical diagnostic factors.</p>
      </div>
    );
  }

  return (
    <div className="bg-surface/90 border border-surface-border rounded-2xl p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-5 border-b border-surface-border">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-mono uppercase text-accent font-semibold">Rank #{hotspot.rank} Corridor Hotspot</span>
            <span className="text-slate-400">•</span>
            <span className="text-xs font-mono text-slate-400">{hotspot.area}</span>
          </div>
          <h3 className="text-2xl font-bold text-white tracking-tight">{hotspot.road}</h3>
          <p className="text-xs text-slate-400 mt-0.5">{hotspot.corridorType || 'Arterial Urban Highway'}</p>
        </div>
        <PredictionBadge category={hotspot.congestionCategory} score={hotspot.predictedCongestion} size="default" />
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-3 gap-3 font-mono text-center">
        <div className="p-3.5 rounded-xl bg-background/80 border border-surface-border">
          <span className="text-[10px] text-slate-400 uppercase block mb-1">Predicted Speed</span>
          <span className="text-xl font-bold text-white">{hotspot.predictedSpeed}</span>
          <span className="text-[10px] text-slate-400 block">km/h baseline</span>
        </div>
        <div className="p-3.5 rounded-xl bg-background/80 border border-surface-border">
          <span className="text-[10px] text-slate-400 uppercase block mb-1">Traffic Flow</span>
          <span className="text-xl font-bold text-white">{hotspot.predictedTrafficVolume.toLocaleString()}</span>
          <span className="text-[10px] text-slate-400 block">veh / day</span>
        </div>
        <div className="p-3.5 rounded-xl bg-background/80 border border-surface-border">
          <span className="text-[10px] text-slate-400 uppercase block mb-1">Capacity Saturation</span>
          <span className="text-xl font-bold text-amber-400">{hotspot.capacityUtilization || '96.2%'}</span>
          <span className="text-[10px] text-slate-400 block">design limit</span>
        </div>
      </div>

      {/* Contributing Factors (from ML explainability) */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <Activity className="w-4 h-4 text-accent" />
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200 font-mono">
            Model Explanation & Contributing Indicators
          </h4>
        </div>
        <div className="space-y-2 text-xs">
          {hotspot.contributingFactors && hotspot.contributingFactors.map((factor, idx) => (
            <div
              key={idx}
              className="p-3 rounded-lg bg-surface-elevated/40 border border-surface-border/70 flex items-start gap-2.5 text-slate-300"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-accent mt-1.5 shrink-0" />
              <span>{factor}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Model vs Observed Baseline Footnote */}
      <div className="p-3.5 rounded-xl bg-surface-elevated/20 border border-surface-border/40 text-[11px] text-slate-400 leading-relaxed font-mono">
        <span className="text-slate-300 font-semibold block mb-0.5">Model Methodology:</span>
        Forecast generated by Random Forest regressor with chronological training (Test MAE 16.34). Excludes current-day target leakage. Based strictly on historical lag persistence, area geometry, and local capacity constraints.
      </div>
    </div>
  );
}
