/**
 * CITYFLOW AI - Central Cities Configuration
 * India-wide urban hubs for navigation and traffic intelligence.
 */

export const CITIES = [
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    zoom: 12,
    hasTrafficModel: true,
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.3850,
    longitude: 78.4867,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.0760,
    longitude: 72.8777,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'delhi',
    name: 'Delhi NCR',
    state: 'Delhi',
    country: 'India',
    latitude: 28.6139,
    longitude: 77.2090,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'pune',
    name: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5204,
    longitude: 73.8567,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0827,
    longitude: 80.2707,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    latitude: 22.5726,
    longitude: 88.3639,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    latitude: 23.0225,
    longitude: 72.5714,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    latitude: 26.9124,
    longitude: 75.7873,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 26.8467,
    longitude: 80.9462,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'surat',
    name: 'Surat',
    state: 'Gujarat',
    country: 'India',
    latitude: 21.1702,
    longitude: 72.8311,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'kochi',
    name: 'Kochi',
    state: 'Kerala',
    country: 'India',
    latitude: 9.9312,
    longitude: 76.2673,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'indore',
    name: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    latitude: 22.7196,
    longitude: 75.8577,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'bhopal',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    country: 'India',
    latitude: 23.2599,
    longitude: 77.4126,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'nagpur',
    name: 'Nagpur',
    state: 'Maharashtra',
    country: 'India',
    latitude: 21.1458,
    longitude: 79.0882,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'coimbatore',
    name: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.0168,
    longitude: 76.9558,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 17.6868,
    longitude: 83.2185,
    zoom: 12,
    hasTrafficModel: false,
  },
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    state: 'Punjab & Haryana',
    country: 'India',
    latitude: 30.7333,
    longitude: 76.7794,
    zoom: 12,
    hasTrafficModel: false,
  },
];

export const getCityById = (id) =>
  CITIES.find((c) => c.id.toLowerCase() === (id || '').toLowerCase()) || CITIES[0];

export const getDefaultCity = () => CITIES[0];
